# server/api/batch_adsorption.py
"""
Batch H-adsorption workflow: generate structures, submit to HPC, collect results.

MVP endpoint for running H adsorption on multiple metals and sites via Hoffman2 PBS.
"""
from __future__ import annotations

import logging
import os
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from server.execution.structure_agent import (
    _build_slab,
    _guess_crystal_system,
    find_adsorption_sites_ase,
    place_adsorbate,
    _atoms_to_poscar,
)
from server.execution.ase_scripts import script_geo
from server.settings import settings, get_server
from server import sshio

_log = logging.getLogger("chatdft.batch_adsorption")

router = APIRouter(prefix="/api", tags=["batch-adsorption"])

# Magnetic elements that need ISPIN=2
_MAGNETIC = {"Fe", "Co", "Ni", "Cr", "Mn"}


# ── Request / Response models ────────────────────────────────────────────

class BatchAdsorptionRequest(BaseModel):
    adsorbate: str = Field("H", description="Adsorbate molecule (H, CO, OH, etc.)")
    metals: List[str] = Field(["Pt", "Pd", "Ni"], description="Metal elements")
    facet: str = Field("111", description="Surface facet (111, 100, 110)")
    sites: List[str] = Field(
        ["ontop", "bridge", "hollow"],
        description="Adsorption site types to compute",
    )
    supercell: str = Field("3x4", description="Supercell size (e.g. 3x4, 4x4). ny must be even for fcc111.")
    nlayers: int = Field(4, description="Number of slab layers")
    vacuum: float = Field(15.0, description="Vacuum thickness in Angstrom")
    fix_layers: int = Field(2, description="Number of bottom layers to fix")
    encut: int = Field(400, description="VASP ENCUT in eV")
    kpoints: str = Field("4 4 1", description="KPOINTS mesh")
    server_name: str = Field("hoffman2", description="HPC server name from config")
    include_references: bool = Field(
        True, description="Also compute clean slabs and gas-phase molecule for E_ads"
    )


class BatchAdsorptionResponse(BaseModel):
    ok: bool
    batch_uid: str = ""
    n_jobs: int = 0
    jobs: List[Dict[str, Any]] = []
    error: str = ""


# ── Helpers ──────────────────────────────────────────────────────────────

def _parse_supercell(s: str):
    parts = s.lower().replace("×", "x").split("x")
    if len(parts) >= 2:
        return int(parts[0]), int(parts[1])
    return int(parts[0]), int(parts[0])


def _place_at_site_type(slab, adsorbate: str, site_type: str, height: float = 1.8):
    """Place adsorbate at a specific site type (ontop/bridge/hollow/fcc/hcp)."""
    from ase import Atoms
    sites = find_adsorption_sites_ase(slab, height=height)

    # Normalize site type names for matching
    type_map = {
        "top": ["ontop", "top"],
        "ontop": ["ontop", "top"],
        "bridge": ["bridge"],
        "fcc": ["hollow", "hollow_fcc", "fcc"],
        "hcp": ["hollow_hcp", "hcp"],
        "hollow": ["hollow", "hollow_fcc", "hollow_hcp", "fcc", "hcp"],
    }
    accept = type_map.get(site_type.lower(), [site_type.lower()])

    matching = [s for s in sites if s.get("type", "").lower() in accept]
    if not matching:
        _log.warning("No %s site found, using first available site", site_type)
        matching = sites

    if not matching:
        raise ValueError(f"No adsorption sites found on slab")

    site = matching[0]
    return place_adsorbate(slab, site["position"], adsorbate)


def _generate_ase_vasp_script(
    metal: str, adsorbate: str, site: str,
    encut: int, kpoints: str, is_reference: bool = False,
) -> str:
    """Generate a self-contained ASE+VASP geometry optimization script."""
    kpts = [int(x) for x in kpoints.split()]
    ispin = 2 if metal in _MAGNETIC else 1

    if is_reference and adsorbate in ("H2", "N2", "O2", "CO"):
        # Gas-phase molecule: Gamma-only, no relaxation of cell
        kpts = [1, 1, 1]
        isif = 0
        desc = f"Gas-phase {adsorbate}"
    else:
        isif = 2
        desc = f"{adsorbate} on {metal}(111) {site}" if not is_reference else f"Clean {metal}(111) slab"

    script = f'''#!/usr/bin/env python3
"""
{desc}
Generated by ChatDFT batch_adsorption
"""
import os
import csv
from ase.io import read, write
from ase.calculators.vasp import Vasp

atoms = read('POSCAR')

calc = Vasp(
    ibrion=2, nsw=200, isif={isif},
    ediffg=-0.02, ediff=1e-5,
    encut={encut},
    kpts={kpts},
    ispin={ispin},
    xc='PBE', gamma=True,
    lwave=False, lcharg=False,
    ncore=4, algo='Fast',
    ismear=1, sigma=0.2,
    lreal='Auto',
)
atoms.calc = calc
energy = atoms.get_potential_energy()
forces = atoms.get_forces()

max_force = max(((f**2).sum())**0.5 for f in forces)

# Write results CSV
with open('ase_results.csv', 'w', newline='') as f:
    w = csv.writer(f)
    w.writerow(['step', 'energy', 'max_force', 'n_atoms', 'converged'])
    w.writerow(['final', f'{{energy:.6f}}', f'{{max_force:.6f}}', len(atoms), max_force < 0.02])

write('CONTCAR_OPT', atoms, format='vasp')
print(f'Energy: {{energy:.4f}} eV')
print(f'Max force: {{max_force:.4f}} eV/Ang')
'''
    return script


def _generate_pbs_script(title: str, svr: dict) -> str:
    """Generate PBS submission script from server template."""
    from jinja2 import Template
    tmpl = Template(svr["sh_template"])
    return tmpl.render(title=title, ppn=4, walltime="04:00:00")


# ── Main endpoint ────────────────────────────────────────────────────────

@router.post("/batch_adsorption", response_model=BatchAdsorptionResponse)
async def batch_adsorption(req: BatchAdsorptionRequest):
    """
    Submit a batch of H-adsorption calculations to HPC.

    Generates structures for each (metal, site) combination,
    creates VASP input files, and submits to the PBS queue.
    """
    batch_uid = str(uuid.uuid4())
    svr = get_server(req.server_name)
    nx, ny = _parse_supercell(req.supercell)
    jobs_info = []

    try:
        job_list = []

        # Build the job list: adsorption calculations
        for metal in req.metals:
            for site in req.sites:
                job_list.append({
                    "metal": metal,
                    "site": site,
                    "adsorbate": req.adsorbate,
                    "is_reference": False,
                    "title": f"H-{metal}{req.facet}-{site}",
                })

        # Reference calculations for E_ads
        if req.include_references:
            for metal in req.metals:
                job_list.append({
                    "metal": metal,
                    "site": "clean",
                    "adsorbate": "",
                    "is_reference": True,
                    "title": f"slab-{metal}{req.facet}-clean",
                })
            # Gas-phase H2
            job_list.append({
                "metal": "",
                "site": "gas",
                "adsorbate": "H2",
                "is_reference": True,
                "title": "gas-H2",
            })

        # Process each job
        for job_spec in job_list:
            metal = job_spec["metal"]
            site = job_spec["site"]
            adsorbate = job_spec["adsorbate"]
            title = job_spec["title"]
            is_ref = job_spec["is_reference"]

            job_uid = str(uuid.uuid4())

            # Build structure
            if is_ref and site == "gas":
                # Gas-phase H2 molecule
                from ase import Atoms
                h2 = Atoms("H2", positions=[[0, 0, 0], [0, 0, 0.74]])
                h2.set_cell([15, 15, 15])
                h2.center()
                poscar = _atoms_to_poscar(h2)
            else:
                crystal = _guess_crystal_system(metal, {})
                h, k, l = int(req.facet[0]), int(req.facet[1]), int(req.facet[2])
                slab = _build_slab(metal, crystal, h, k, l, nx, ny, req.nlayers, req.vacuum)

                # Fix bottom layers
                from ase.constraints import FixAtoms
                import numpy as np
                positions = slab.get_positions()
                z_coords = positions[:, 2]
                z_sorted = sorted(set(round(z, 1) for z in z_coords))
                if len(z_sorted) >= req.fix_layers + 1:
                    z_cutoff = z_sorted[req.fix_layers - 1] + 0.5
                    fix_idx = [i for i, z in enumerate(z_coords) if z < z_cutoff]
                    slab.set_constraint(FixAtoms(indices=fix_idx))

                if not is_ref:
                    slab = _place_at_site_type(slab, adsorbate, site)

                poscar = _atoms_to_poscar(slab)

            # Generate scripts
            ase_script = _generate_ase_vasp_script(
                metal=metal or "H",
                adsorbate=adsorbate or "slab",
                site=site,
                encut=req.encut,
                kpoints=req.kpoints,
                is_reference=is_ref,
            )
            pbs_script = _generate_pbs_script(title, svr)

            # Write local files
            ts = datetime.now().strftime("%Y%m%d-%H%M%S")
            local_dir = os.path.join(settings.LOCAL_RUNS, f"{title}_{ts}_{job_uid[:8]}")
            os.makedirs(local_dir, exist_ok=True)

            with open(os.path.join(local_dir, "POSCAR"), "w") as f:
                f.write(poscar)
            with open(os.path.join(local_dir, "ase-opt.py"), "w") as f:
                f.write(ase_script)
            with open(os.path.join(local_dir, "ase.sh"), "w") as f:
                f.write(pbs_script)

            # Push to HPC and submit (with retry for SSH rate-limiting)
            import time
            pbs_id = ""
            for attempt in range(3):
                try:
                    sshio.ensure_remote_dir(job_uid, svr)
                    sshio.push_files(job_uid, local_dir, svr)
                    pbs_id = sshio.submit(job_uid, svr)
                    break
                except Exception as ssh_err:
                    _log.warning("SSH attempt %d failed for %s: %s", attempt + 1, title, ssh_err)
                    if attempt < 2:
                        time.sleep(3 * (attempt + 1))  # 3s, 6s backoff
                    else:
                        raise

            # Brief pause between jobs to avoid SSH rate-limiting
            time.sleep(2)

            jobs_info.append({
                "job_uid": job_uid,
                "title": title,
                "metal": metal,
                "site": site,
                "adsorbate": adsorbate,
                "is_reference": is_ref,
                "pbs_id": pbs_id,
                "local_dir": local_dir,
                "status": "submitted",
            })

            _log.info("Submitted %s → PBS %s", title, pbs_id)

        # Register batch for status tracking
        from server.api.batch_results import register_batch
        register_batch(batch_uid, jobs_info)

        return BatchAdsorptionResponse(
            ok=True,
            batch_uid=batch_uid,
            n_jobs=len(jobs_info),
            jobs=jobs_info,
        )

    except Exception as e:
        _log.exception("Batch adsorption failed")
        return BatchAdsorptionResponse(ok=False, error=str(e))
