"""add hypothesis sheet, wiki, paper, knowledge sheet

Revision ID: 2605fe1c581f
Revises: c066be6e46ea
Create Date: 2025-07-26 20:46:05.145514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2605fe1c581f'
down_revision: Union[str, Sequence[str], None] = 'c066be6e46ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_object_phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=True),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_object_phrase')
    # ### end Alembic commands ###
