"""add Knowledge.doi + indexes

Revision ID: 5d67705bdcb2
Revises: 8c0b5acfebfa
Create Date: 2025-08-07 20:13:02.419602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d67705bdcb2'
down_revision: Union[str, Sequence[str], None] = '8c0b5acfebfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('adsorption_structure_slab_id_fkey'), 'adsorption_structure', type_='foreignkey')
    op.create_foreign_key(None, 'adsorption_structure', 'slab_structure', ['slab_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_chatmessage_role', 'chat_message', ['role'], unique=False)
    op.create_index('idx_chatmessage_session_id', 'chat_message', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_message_role'), 'chat_message', ['role'], unique=False)
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False)
    op.drop_constraint(op.f('chat_message_session_id_fkey'), 'chat_message', type_='foreignkey')
    op.create_foreign_key(None, 'chat_message', 'chat_session', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('hypothesis', 'hypothesis',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('hypothesis_message_id_fkey'), 'hypothesis', type_='foreignkey')
    op.drop_constraint(op.f('hypothesis_session_id_fkey'), 'hypothesis', type_='foreignkey')
    op.create_foreign_key(None, 'hypothesis', 'chat_session', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'hypothesis', 'chat_message', ['message_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('job_schedule_calculation_id_fkey'), 'job_schedule', type_='foreignkey')
    op.create_foreign_key(None, 'job_schedule', 'calculation_parameter', ['calculation_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge', sa.Column('doi', sa.String(), nullable=True))
    op.create_unique_constraint('_knowledge_doi_uc', 'knowledge', ['doi'])
    op.create_unique_constraint('_knowledge_src_uc', 'knowledge', ['source_type', 'source_id'])
    op.create_index(op.f('ix_knowledge_doi'), 'knowledge', ['doi'], unique=False)
    op.drop_constraint(op.f('post_analysis_calculation_id_fkey'), 'post_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'post_analysis', 'calculation_parameter', ['calculation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('slab_structure_bulk_id_fkey'), 'slab_structure', type_='foreignkey')
    op.create_foreign_key(None, 'slab_structure', 'bulk_structure', ['bulk_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_workflowtask_agent', 'workflow_task', ['agent'], unique=False)
    op.create_index('idx_workflowtask_name', 'workflow_task', ['name'], unique=False)
    op.create_index('idx_workflowtask_session_id', 'workflow_task', ['session_id'], unique=False)
    op.create_index('idx_workflowtask_status', 'workflow_task', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_task_session_id'), 'workflow_task', ['session_id'], unique=False)
    op.drop_constraint(op.f('workflow_task_message_id_fkey'), 'workflow_task', type_='foreignkey')
    op.drop_constraint(op.f('workflow_task_session_id_fkey'), 'workflow_task', type_='foreignkey')
    op.drop_constraint(op.f('workflow_task_parent_task_id_fkey'), 'workflow_task', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_task', 'chat_message', ['message_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workflow_task', 'workflow_task', ['parent_task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workflow_task', 'chat_session', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_task', type_='foreignkey')
    op.drop_constraint(None, 'workflow_task', type_='foreignkey')
    op.drop_constraint(None, 'workflow_task', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_task_parent_task_id_fkey'), 'workflow_task', 'workflow_task', ['parent_task_id'], ['id'])
    op.create_foreign_key(op.f('workflow_task_session_id_fkey'), 'workflow_task', 'chat_session', ['session_id'], ['id'])
    op.create_foreign_key(op.f('workflow_task_message_id_fkey'), 'workflow_task', 'chat_message', ['message_id'], ['id'])
    op.drop_index(op.f('ix_workflow_task_session_id'), table_name='workflow_task')
    op.drop_index('idx_workflowtask_status', table_name='workflow_task')
    op.drop_index('idx_workflowtask_session_id', table_name='workflow_task')
    op.drop_index('idx_workflowtask_name', table_name='workflow_task')
    op.drop_index('idx_workflowtask_agent', table_name='workflow_task')
    op.drop_constraint(None, 'slab_structure', type_='foreignkey')
    op.create_foreign_key(op.f('slab_structure_bulk_id_fkey'), 'slab_structure', 'bulk_structure', ['bulk_id'], ['id'])
    op.drop_constraint(None, 'post_analysis', type_='foreignkey')
    op.create_foreign_key(op.f('post_analysis_calculation_id_fkey'), 'post_analysis', 'calculation_parameter', ['calculation_id'], ['id'])
    op.drop_index(op.f('ix_knowledge_doi'), table_name='knowledge')
    op.drop_constraint('_knowledge_src_uc', 'knowledge', type_='unique')
    op.drop_constraint('_knowledge_doi_uc', 'knowledge', type_='unique')
    op.drop_column('knowledge', 'doi')
    op.drop_constraint(None, 'job_schedule', type_='foreignkey')
    op.create_foreign_key(op.f('job_schedule_calculation_id_fkey'), 'job_schedule', 'calculation_parameter', ['calculation_id'], ['id'])
    op.drop_constraint(None, 'hypothesis', type_='foreignkey')
    op.drop_constraint(None, 'hypothesis', type_='foreignkey')
    op.create_foreign_key(op.f('hypothesis_session_id_fkey'), 'hypothesis', 'chat_session', ['session_id'], ['id'])
    op.create_foreign_key(op.f('hypothesis_message_id_fkey'), 'hypothesis', 'chat_message', ['message_id'], ['id'])
    op.alter_column('hypothesis', 'hypothesis',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.create_foreign_key(op.f('chat_message_session_id_fkey'), 'chat_message', 'chat_session', ['session_id'], ['id'])
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_role'), table_name='chat_message')
    op.drop_index('idx_chatmessage_session_id', table_name='chat_message')
    op.drop_index('idx_chatmessage_role', table_name='chat_message')
    op.drop_constraint(None, 'adsorption_structure', type_='foreignkey')
    op.create_foreign_key(op.f('adsorption_structure_slab_id_fkey'), 'adsorption_structure', 'slab_structure', ['slab_id'], ['id'])
    # ### end Alembic commands ###
