"""enrich workflow_task and material table all

Revision ID: 91260d4df8ef
Revises: 33b47a64f63f
Create Date: 2025-07-26 19:53:49.900054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91260d4df8ef'
down_revision: Union[str, Sequence[str], None] = '33b47a64f63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intent_phrase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('example_type', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent', 'phrase', name='_intent_phrase_uc')
    )
    op.add_column('chat_message', sa.Column('msg_type', sa.String(), nullable=True))
    op.add_column('chat_message', sa.Column('intent', sa.String(), nullable=True))
    op.add_column('chat_message', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('chat_message', sa.Column('llm_model', sa.String(), nullable=True))
    op.add_column('chat_message', sa.Column('source', sa.String(), nullable=True))
    op.add_column('chat_message', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('chat_message', sa.Column('attachments', sa.JSON(), nullable=True))
    op.add_column('chat_message', sa.Column('references', sa.JSON(), nullable=True))
    op.add_column('chat_message', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('chat_message', sa.Column('token_usage', sa.Integer(), nullable=True))
    op.add_column('chat_message', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('chat_message', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('chat_session', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('chat_session', sa.Column('project', sa.String(), nullable=True))
    op.add_column('chat_session', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('chat_session', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('chat_session', sa.Column('status', sa.String(), nullable=True))
    op.add_column('chat_session', sa.Column('pinned', sa.Boolean(), nullable=True))
    op.add_column('chat_session', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('chat_session', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('material', sa.Column('mp_id', sa.String(), nullable=True))
    op.add_column('material', sa.Column('structure_type', sa.String(), nullable=True))
    op.add_column('material', sa.Column('dimensionality', sa.Integer(), nullable=True))
    op.add_column('material', sa.Column('spacegroup', sa.String(), nullable=True))
    op.add_column('material', sa.Column('lattice_params', sa.JSON(), nullable=True))
    op.add_column('material', sa.Column('elements', sa.JSON(), nullable=True))
    op.add_column('material', sa.Column('bandgap', sa.Float(), nullable=True))
    op.add_column('material', sa.Column('magnetic', sa.String(), nullable=True))
    op.add_column('material', sa.Column('status', sa.String(), nullable=True))
    op.add_column('material', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('material', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('material', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('workflow_task', sa.Column('intent', sa.String(), nullable=True))
    op.add_column('workflow_task', sa.Column('input_data', sa.JSON(), nullable=True))
    op.add_column('workflow_task', sa.Column('output_data', sa.JSON(), nullable=True))
    op.add_column('workflow_task', sa.Column('parent_task_id', sa.Integer(), nullable=True))
    op.add_column('workflow_task', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('workflow_task', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('workflow_task', sa.Column('run_time', sa.Float(), nullable=True))
    op.add_column('workflow_task', sa.Column('error_msg', sa.Text(), nullable=True))
    op.add_column('workflow_task', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('workflow_task', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'workflow_task', 'workflow_task', ['parent_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_task', type_='foreignkey')
    op.drop_column('workflow_task', 'updated_at')
    op.drop_column('workflow_task', 'owner')
    op.drop_column('workflow_task', 'error_msg')
    op.drop_column('workflow_task', 'run_time')
    op.drop_column('workflow_task', 'tags')
    op.drop_column('workflow_task', 'priority')
    op.drop_column('workflow_task', 'parent_task_id')
    op.drop_column('workflow_task', 'output_data')
    op.drop_column('workflow_task', 'input_data')
    op.drop_column('workflow_task', 'intent')
    op.drop_column('material', 'updated_at')
    op.drop_column('material', 'owner')
    op.drop_column('material', 'tags')
    op.drop_column('material', 'status')
    op.drop_column('material', 'magnetic')
    op.drop_column('material', 'bandgap')
    op.drop_column('material', 'elements')
    op.drop_column('material', 'lattice_params')
    op.drop_column('material', 'spacegroup')
    op.drop_column('material', 'dimensionality')
    op.drop_column('material', 'structure_type')
    op.drop_column('material', 'mp_id')
    op.drop_column('chat_session', 'meta')
    op.drop_column('chat_session', 'updated_at')
    op.drop_column('chat_session', 'pinned')
    op.drop_column('chat_session', 'status')
    op.drop_column('chat_session', 'description')
    op.drop_column('chat_session', 'tags')
    op.drop_column('chat_session', 'project')
    op.drop_column('chat_session', 'user_id')
    op.drop_column('chat_message', 'updated_at')
    op.drop_column('chat_message', 'duration')
    op.drop_column('chat_message', 'token_usage')
    op.drop_column('chat_message', 'feedback')
    op.drop_column('chat_message', 'references')
    op.drop_column('chat_message', 'attachments')
    op.drop_column('chat_message', 'parent_id')
    op.drop_column('chat_message', 'source')
    op.drop_column('chat_message', 'llm_model')
    op.drop_column('chat_message', 'confidence')
    op.drop_column('chat_message', 'intent')
    op.drop_column('chat_message', 'msg_type')
    op.drop_table('intent_phrase')
    # ### end Alembic commands ###
