"""add hypothesis sheet, wiki, paper, knowledge sheet

Revision ID: c066be6e46ea
Revises: c2c0158a9890
Create Date: 2025-07-26 20:25:27.876322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c066be6e46ea'
down_revision: Union[str, Sequence[str], None] = 'c2c0158a9890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
