# server/execution/ase_scripts.py
# -*- coding: utf-8 -*-
"""
ASE calculation script templates.
Each function returns a complete Python script string ready to run with ASE+VASP.

Scripts generated:
  ase-surface.py   — build clean slab (fcc111/bcc110/hcp0001)
  ase-molecule.py  — build gas-phase molecule from PubChem
  ase-geo.py       — geometry optimization (ISIF=2 or 0)
  ase-freq.py      — frequency / ZPE / entropy (IBRION=5)
  ase-neb.py       — CI-NEB transition state search
  ase-gcdft.py     — grand-canonical DFT / VASPsol potential sweep
  ase-dos.py       — DOS / PDOS calculation (non-SCF, ICHARG=11)
  ase-band.py      — band structure (HSE or PBE, non-SCF)
  ase-elf.py       — electron localization function (NCORE=1 required)
  ase-static.py    — static SCF (writes WAVECAR+CHGCAR for follow-ups)
  ase-bader.py     — Bader charge analysis (LAECHG=True)
  ase-cdd.py       — charge density difference (3 static calcs)
  ase-wf.py        — work function (LVHAR=True, LOCPOT parsing)
  ase-cohp.py      — COHP bonding analysis (ISYM=-1, LOBSTER input)
"""
from __future__ import annotations
from typing import Any, Dict

# ─────────────────────────────────────────────────────────────────────────────
# SMILES quick-lookup used in surface/molecule scripts
# ─────────────────────────────────────────────────────────────────────────────
_SMILES: Dict[str, str] = {
    "C4H10": "CCCC", "C4H8": "C=CCC", "C4H8_2": "CC=CC",
    "C3H8": "CCC", "C3H6": "C=CC", "C2H6": "CC", "C2H4": "C=C",
    "CH4": "C", "CO2": "O=C=O", "CO": "[C-]#[O+]",
    "H2O": "O", "NH3": "N", "H2": "[HH]", "N2": "N#N",
}


def _header(title: str) -> str:
    return f"#!/usr/bin/env python3\n# -*- coding: utf-8 -*-\n\"\"\"\n{title}\nGenerated by ChatDFT — edit parameters as needed.\n\"\"\"\n"


# ─────────────────────────────────────────────────────────────────────────────
# 1. Surface builder
# ─────────────────────────────────────────────────────────────────────────────
def script_surface(
    element: str = "Ag",
    surface_type: str = "111",
    nx: int = 4, ny: int = 4, nlayers: int = 3,
    vacuum: float = 10.0,
    fix_bottom: bool = True,
    **_kw,
) -> str:
    build_fn = {
        "111": "fcc111", "100": "fcc100", "110": "fcc110",
        "0001": "hcp0001", "10m10": "hcp10m10",
        "bcc110": "bcc110", "bcc100": "bcc100",
    }.get(surface_type, "fcc111")

    lines = [
        _header(f"Build {element}({surface_type}) {nx}×{ny}×{nlayers} slab, vacuum={vacuum} Å"),
        "from ase.io.vasp import write_vasp",
        f"from ase.build import {build_fn}, add_adsorbate",
        "import ase.constraints",
        "import numpy as np",
        "",
        f"# Build {element}({surface_type}) slab  (size = ({nx},{ny},{nlayers}), vacuum = {vacuum} Å)",
        f"slab = {build_fn}('{element}', size=({nx},{ny},{nlayers}), vacuum={vacuum})",
        "",
    ]
    if fix_bottom:
        lines += [
            "# Fix bottom layer atoms",
            "base_z = np.array([atom.z for atom in slab]).min()",
            "base_layer_index = [atom.index for atom in slab if abs(base_z - atom.z) < 0.1]",
            "constraints = ase.constraints.FixAtoms(indices=base_layer_index)",
            "slab.set_constraint(constraints)",
            "",
        ]
    lines += [
        "# Write POSCAR",
        "write_vasp('POSCAR', slab)",
        f"print(f'Written POSCAR: {{len(slab)}} atoms, {element}({surface_type})-{nx}x{ny}x{nlayers}')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 2. Molecule builder (PubChem)
# ─────────────────────────────────────────────────────────────────────────────
def script_molecule(
    formula: str = "C4H10",
    smiles: str = "",
    cell_size: float = 20.0,
    **_kw,
) -> str:
    smiles = smiles or _SMILES.get(formula, formula)
    lines = [
        _header(f"Fetch {formula} from PubChem and write POSCAR"),
        "from ase.io.vasp import write_vasp",
        "from ase.data.pubchem import pubchem_atoms_search",
        "",
        f"# Search PubChem by SMILES: {smiles}",
        f"mol = pubchem_atoms_search(smiles='{smiles}')",
        f"mol.set_cell([{cell_size}, {cell_size}, {cell_size}])",
        "mol.center()",
        "",
        "write_vasp('POSCAR', mol)",
        f"print(f'Written POSCAR: {{mol.get_chemical_formula()}} ({{len(mol)}} atoms)')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 3. Geometry optimisation
# ─────────────────────────────────────────────────────────────────────────────
def script_geo(
    kpoints: str = "4 4 1",
    encut: int = 400,
    ediffg: float = -0.02,
    isif: int = 2,
    nsw: int = 200,
    is_molecule: bool = False,
    system_desc: str = "",
    **_kw,
) -> str:
    kpts = [int(x) for x in kpoints.replace("x"," ").split()[:3]] if kpoints else [4,4,1]
    if is_molecule:
        kpts = [1,1,1]
        isif = 0
    lines = [
        _header(f"Geometry optimisation — {system_desc or 'surface slab'}"),
        "from ase.io import read, write",
        "from ase.calculators.vasp import Vasp",
        "",
        "atoms = read('POSCAR')",
        "",
        "calc = Vasp(",
        f"    ibrion=2, nsw={nsw}, isif={isif},",
        f"    ediffg={ediffg}, ediff=1e-5,",
        f"    encut={encut},",
        f"    kpts={kpts},",
        "    xc='PBE', gamma=True,",
        "    lwave=False, lcharg=False,",
        "    ncore=4, algo='Fast',",
        ")",
        "atoms.set_calculator(calc)",
        "atoms.get_potential_energy()   # triggers VASP run",
        "",
        "write('CONTCAR_OPT', atoms, format='vasp')",
        "print(f'Energy: {atoms.get_potential_energy():.4f} eV')",
        "print(f'Max force: {max(((f**2).sum())**0.5 for f in atoms.get_forces()):.4f} eV/Å')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 4. Frequency / ZPE
# ─────────────────────────────────────────────────────────────────────────────
def script_freq(
    kpoints: str = "4 4 1",
    encut: int = 400,
    potim: float = 0.015,
    nfree: int = 2,
    temperature: float = 500.0,
    adsorbate: str = "",
    **_kw,
) -> str:
    kpts = [int(x) for x in kpoints.replace("x"," ").split()[:3]] if kpoints else [4,4,1]
    lines = [
        _header(f"Frequency / ZPE calculation — {adsorbate or 'adsorbed species'}"),
        "from ase.io import read",
        "from ase.calculators.vasp import Vasp",
        "from ase.thermochemistry import HarmonicThermo",
        "import numpy as np",
        "",
        "atoms = read('CONTCAR')   # use relaxed geometry from geo opt",
        "",
        "# IBRION=5: finite-difference Hessian (does NOT move atoms, NSW=1)",
        "calc = Vasp(",
        "    ibrion=5, nfree=2, nsw=1, isif=0,",
        f"    potim={potim},",
        "    ediff=1e-7,",
        f"    encut={encut},",
        f"    kpts={kpts},",
        "    xc='PBE', gamma=True,",
        "    lwave=False, lcharg=False,",
        "    ncore=4,",
        ")",
        "atoms.set_calculator(calc)",
        "atoms.get_potential_energy()",
        "",
        "# Extract vibrational frequencies from OUTCAR",
        "from ase.io import read as _read",
        "vib_energies = []",
        "with open('OUTCAR') as fh:",
        "    for line in fh:",
        "        if 'meV' in line and 'f  =' in line:",
        "            parts = line.split()",
        "            ev_idx = parts.index('meV') - 1",
        "            vib_energies.append(float(parts[ev_idx]) * 1e-3)  # meV → eV",
        "        elif 'meV' in line and 'f/i=' in line:",
        "            pass  # imaginary — skip for thermo",
        "",
        "if vib_energies:",
        f"    thermo = HarmonicThermo(vib_energies=vib_energies)",
        f"    T = {temperature}",
        "    ZPE = thermo.get_ZPE_correction()",
        "    S   = thermo.get_entropy(T)",
        "    H   = thermo.get_enthalpy(T)",
        "    G   = thermo.get_helmholtz_energy(T, verbose=True)",
        "    print(f'T={T} K   ZPE={ZPE:.4f} eV   S={S*1e3:.2f} meV/K   G={G:.4f} eV')",
        "    # Save summary",
        "    with open('thermo_summary.txt','w') as out:",
        "        out.write(f'T={T} K\\nZPE={ZPE:.6f} eV\\nS={S:.6e} eV/K\\nG={G:.6f} eV\\n')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 5. CI-NEB
# ─────────────────────────────────────────────────────────────────────────────
def script_neb(
    n_images: int = 7,
    kpoints: str = "4 4 1",
    encut: int = 400,
    spring: float = -5.0,
    ediffg: float = -0.05,
    step: str = "",
    **_kw,
) -> str:
    kpts = [int(x) for x in kpoints.replace("x"," ").split()[:3]] if kpoints else [4,4,1]
    lines = [
        _header(f"CI-NEB for: {step or 'elementary step'}"),
        "import os",
        "from ase.io import read, write",
        "from ase.calculators.vasp import Vasp",
        "from ase.neb import NEB",
        "from ase.optimize import BFGS",
        "",
        "# Load initial state (IS) and final state (FS)",
        "initial = read('IS/CONTCAR')  # relaxed initial state",
        "final   = read('FS/CONTCAR')  # relaxed final state",
        "",
        f"n_images = {n_images}",
        "images = [initial.copy() for _ in range(n_images + 2)]",
        "images[-1] = final.copy()",
        "",
        "# Interpolate intermediate images",
        "neb = NEB(images, climb=True, allow_shared_calculator=True)",
        "neb.interpolate()",
        "",
        "# Assign VASP calculators to each image",
        "for i, img in enumerate(images[1:-1]):",
        "    img.calc = Vasp(",
        "        ibrion=3, potim=0, nsw=200, isif=2,",
        "        images=n_images,",
        "        lclimb=True,",
        f"        spring={spring},",
        "        ichain=0, lnebcell=False,",
        f"        ediffg={ediffg}, ediff=1e-5,",
        f"        encut={encut},",
        f"        kpts={kpts},",
        "        xc='PBE', gamma=True,",
        "        lwave=False, lcharg=False,",
        "        ncore=4,",
        f"        directory=f'image_{{i+1:02d}}',",
        "    )",
        "",
        "opt = BFGS(neb, trajectory='neb.traj')",
        "opt.run(fmax=0.05)",
        "",
        "# Print barrier",
        "energies = [img.get_potential_energy() for img in images]",
        "barrier = max(energies) - energies[0]",
        "print(f'Barrier = {barrier:.3f} eV')",
        "print(f'Reaction energy = {energies[-1]-energies[0]:.3f} eV')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 6. GC-DFT / VASPsol
# ─────────────────────────────────────────────────────────────────────────────
def script_gcdft(
    kpoints: str = "4 4 1",
    encut: int = 400,
    potential_start: float = -1.5,
    potential_end: float = 0.5,
    nelect_step: float = 0.25,
    eb_k: float = 78.4,
    lambda_d: float = 3.0,
    adsorbate: str = "",
    **_kw,
) -> str:
    kpts = [int(x) for x in kpoints.replace("x"," ").split()[:3]] if kpoints else [4,4,1]
    lines = [
        _header(f"GC-DFT / VASPsol potential sweep — {adsorbate or 'surface'}"),
        "import numpy as np",
        "from ase.io import read, write",
        "from ase.calculators.vasp import Vasp",
        "import json",
        "",
        "atoms = read('CONTCAR')   # relaxed adsorption geometry",
        "# Get reference electron count",
        "ref_nelect = None",
        "with open('OUTCAR') as fh:",
        "    for line in fh:",
        "        if 'NELECT' in line and 'number of electrons' in line:",
        "            ref_nelect = float(line.split()[2]); break",
        "if ref_nelect is None:",
        "    ref_nelect = sum(atoms.get_atomic_numbers())  # fallback",
        "",
        f"U_range = np.arange({potential_start}, {potential_end}+0.01, {nelect_step})",
        "results = []",
        "",
        "for U in U_range:",
        f"    delta_nelect = -U / 4.44  # CHE: U vs RHE → ΔNELECT approx",
        "    nelect = ref_nelect + delta_nelect",
        "    calc = Vasp(",
        "        ibrion=2, nsw=100, isif=2,",
        "        ediffg=-0.02, ediff=1e-6,",
        f"        encut={encut},",
        f"        kpts={kpts},",
        "        xc='PBE', gamma=True,",
        "        lwave=False, lcharg=False,",
        "        ncore=4,",
        "        # VASPsol settings",
        "        lsol=True,",
        f"        eb_k={eb_k},",
        f"        lambda_d_debye={lambda_d},",
        "        nelect=int(round(nelect)),",
        "        directory=f'U_{U:.2f}V'.replace('-','m').replace('.','p'),",
        "    )",
        "    atoms_copy = atoms.copy()",
        "    atoms_copy.calc = calc",
        "    try:",
        "        E = atoms_copy.get_potential_energy()",
        "        results.append({'U_V': float(U), 'E_eV': E, 'nelect': int(round(nelect))})",
        "        print(f'U={U:.2f} V  E={E:.4f} eV  NELECT={nelect:.1f}')",
        "    except Exception as e:",
        "        print(f'U={U:.2f} V  FAILED: {e}')",
        "",
        "with open('gcdft_results.json','w') as f:",
        "    json.dump(results, f, indent=2)",
        "print(f'Done: {len(results)} points saved to gcdft_results.json')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 7. DOS / PDOS
# ─────────────────────────────────────────────────────────────────────────────
def script_static(
    kpoints: str = "8 8 1",
    encut: int = 400,
    system_desc: str = "",
    **_kw,
) -> str:
    """Step 1: Self-consistent SCF that writes WAVECAR+CHGCAR for follow-up calcs."""
    kpts = [int(x) for x in kpoints.replace("x"," ").split()[:3]] if kpoints else [8,8,1]
    lines = [
        _header(f"Static SCF — writes WAVECAR+CHGCAR for DOS/band/ELF follow-up — {system_desc or 'surface'}"),
        "from ase.io import read",
        "from ase.calculators.vasp import Vasp",
        "",
        "# Use the RELAXED geometry from a previous geo-opt run",
        "atoms = read('CONTCAR')",
        "",
        "# Step 1 of 2: SCF run — LWAVE+LCHARG=True so DOS/band/ELF can read them",
        "calc = Vasp(",
        "    istart=0, icharg=2,   # fresh SCF",
        "    ibrion=-1, nsw=0,",
        f"    encut={encut},",
        f"    kpts={kpts},",
        "    xc='PBE', gamma=True,",
        "    ismear=1, sigma=0.2,   # Methfessel-Paxton for metals",
        "    ediff=1e-6,",
        "    lwave=True,   # MUST be True — needed by ELF, band, COHP",
        "    lcharg=True,  # MUST be True — needed by DOS, band",
        "    ncore=4, algo='Fast',",
        ")",
        "atoms.set_calculator(calc)",
        "atoms.get_potential_energy()",
        "print('SCF done — WAVECAR and CHGCAR written.')",
        "print('Next: run ase-dos.py / ase-band.py / ase-elf.py in this directory.')",
    ]
    return "\n".join(lines)


def script_dos(
    kpoints: str = "12 12 1",
    encut: int = 400,
    pdos_species: str = "",
    **_kw,
) -> str:
    """Step 2: Non-SCF DOS/PDOS (ICHARG=11). Requires prior SCF run with LCHARG=True."""
    kpts = [int(x) for x in kpoints.replace("x"," ").split()[:3]] if kpoints else [12,12,1]
    lines = [
        _header("DOS / PDOS — non-SCF (Step 2 of 2). Requires CHGCAR from SCF run."),
        "from ase.io import read",
        "from ase.calculators.vasp import Vasp",
        "import numpy as np",
        "",
        "# PREREQUISITE: run ase-static.py first (same directory, same POSCAR/CONTCAR)",
        "atoms = read('CONTCAR')",
        "",
        "# Step 2 of 2: non-SCF with dense k-mesh and tetrahedron smearing",
        "calc = Vasp(",
        "    istart=1, icharg=11,  # non-SCF: reads CHGCAR, does NOT update charge",
        "    ibrion=-1, nsw=0,",
        f"    encut={encut},",
        f"    kpts={kpts},         # denser k-mesh for well-converged DOS",
        "    xc='PBE', gamma=False,",
        "    ismear=-5,            # tetrahedron — no smearing artifacts in DOS",
        "    sigma=0.05,",
        "    lorbit=11,            # lm-decomposed PDOS (s,p,d per atom)",
        "    nedos=2000,",
        "    emin=-15.0, emax=10.0,",
        "    lwave=False, lcharg=False,",
        "    ncore=4,",
        ")",
        "atoms.set_calculator(calc)",
        "atoms.get_potential_energy()",
        "",
        "# Save total DOS",
        "try:",
        "    from ase.dft.dos import DOS as _DOS",
        "    dos_obj = _DOS(calc, width=0.0)",
        "    d = dos_obj.get_dos()",
        "    e = dos_obj.get_energies()",
        "    np.savetxt('dos_total.dat', np.column_stack([e, d]),",
        "               header='energy_eV  DOS_states_per_eV')",
        "    print('Total DOS saved to dos_total.dat')",
        "except Exception as ex:",
        "    print(f'DOS parse warning: {ex}')",
        "",
        "# d-band center from DOSCAR (parse atom-projected d-DOS)",
        "try:",
        "    from ase.calculators.vasp import VaspDos",
        "    dos_vasp = VaspDos('DOSCAR')",
        "    ef = calc.get_fermi_level()",
        "    # Example: d-band of first atom (index 0)",
        "    d_dos = dos_vasp.site_dos(0, 'd')  # integrated over m_l",
        "    e_grid = dos_vasp.energy",
        "    mask = e_grid < ef",
        "    if mask.sum() > 0:",
        "        d_center = np.trapz(e_grid[mask]*d_dos[mask], e_grid[mask]) / np.trapz(d_dos[mask], e_grid[mask])",
        "        print(f'd-band center (atom 0): {d_center:.3f} eV (vs E_F={ef:.3f} eV)')",
        "except Exception as ex:",
        "    print(f'd-band center parse warning: {ex}')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 8. Band structure
# ─────────────────────────────────────────────────────────────────────────────
def script_band(
    encut: int = 400,
    nkpoints: int = 50,
    **_kw,
) -> str:
    lines = [
        _header("Band structure calculation"),
        "from ase.io import read",
        "from ase.calculators.vasp import Vasp",
        "from ase.dft.kpoints import get_special_points, bandpath",
        "",
        "atoms = read('CONTCAR')",
        "lat = atoms.cell.get_bravais_lattice()",
        f"path = lat.bandpath(npoints={nkpoints})",
        "",
        "calc = Vasp(",
        "    istart=1, icharg=11,",
        "    ibrion=-1, nsw=0,",
        f"    encut={encut},",
        "    kpts=path,",
        "    xc='PBE',",
        "    lorbit=11,",
        "    ncore=4,",
        ")",
        "atoms.set_calculator(calc)",
        "atoms.get_potential_energy()",
        "",
        "# Extract and save band energies",
        "try:",
        "    bs = calc.band_structure()",
        "    bs.write('band_structure.json')",
        "    print('Band structure saved to band_structure.json')",
        "except Exception as ex:",
        "    print(f'Band parse error: {ex}')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 9. ELF (electron localization function)
# ─────────────────────────────────────────────────────────────────────────────
def script_elf(encut: int = 400, kpoints: str = "8 8 1", **_kw) -> str:
    """ELF — NCORE=1 is a hard VASP requirement when LELF=True."""
    kpts = [int(x) for x in kpoints.replace("x"," ").split()[:3]] if kpoints else [8,8,1]
    lines = [
        _header("ELF — Electron Localization Function. NCORE=1 required (VASP hard requirement)."),
        "from ase.io import read",
        "from ase.calculators.vasp import Vasp",
        "",
        "# PREREQUISITE: run ase-static.py first to generate WAVECAR",
        "atoms = read('CONTCAR')",
        "",
        "# IMPORTANT: NCORE must be 1 — VASP aborts with NCORE>1 when LELF=True",
        "calc = Vasp(",
        "    istart=1, icharg=0,   # read WAVECAR, do SCF (NOT ICHARG=11 — ELF needs SCF)",
        "    ibrion=-1, nsw=0,",
        f"    encut={encut},",
        f"    kpts={kpts},",
        "    xc='PBE', gamma=True,",
        "    prec='Accurate',",
        "    ediff=1e-6,",
        "    ismear=1, sigma=0.2,",
        "    lelf=True,     # write ELFCAR",
        "    lwave=True, lcharg=True,",
        "    ncore=1,       # *** MANDATORY: VASP aborts if NCORE>1 with LELF=True ***",
        ")",
        "atoms.set_calculator(calc)",
        "atoms.get_potential_energy()",
        "print('ELFCAR written.')",
        "print('Visualize in VESTA: isosurface at ELF=0.75 shows lone pairs and bonds.')",
        "print('ELF=1.0: fully localized (lone pairs)  ELF=0.5: electron gas  ELF=0: depleted')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 10. Bader charge analysis
# ─────────────────────────────────────────────────────────────────────────────
def script_bader(
    encut: int = 520,
    kpoints: str = "8 8 1",
    **_kw,
) -> str:
    """Bader charge analysis: LAECHG=True → AECCAR0/AECCAR2 → bader binary."""
    kpts = [int(x) for x in kpoints.replace("x"," ").split()[:3]] if kpoints else [8,8,1]
    lines = [
        _header("Bader charge analysis — LAECHG=True, then chgsum.pl + bader binary"),
        "from ase.io import read",
        "from ase.calculators.vasp import Vasp",
        "import subprocess, os",
        "",
        "atoms = read('CONTCAR')",
        "",
        "# Higher ENCUT (520 eV) recommended for accurate all-electron charge density",
        "calc = Vasp(",
        "    istart=0, icharg=2,",
        "    ibrion=-1, nsw=0,",
        f"    encut={encut},",
        f"    kpts={kpts},",
        "    xc='PBE', gamma=True,",
        "    prec='Accurate',",
        "    ediff=1e-6,",
        "    ismear=1, sigma=0.2,",
        "    lreal=False,   # reciprocal projection — required for Bader",
        "    laechg=True,   # write AECCAR0 (core) + AECCAR2 (valence)",
        "    lwave=False, lcharg=True,",
        "    ncore=4,",
        ")",
        "atoms.set_calculator(calc)",
        "atoms.get_potential_energy()",
        "print('VASP done — AECCAR0, AECCAR2, CHGCAR written.')",
        "",
        "# ── Post-processing: Bader charge partitioning ──────────────────────────",
        "# Requires: chgsum.pl (VTST scripts) and bader binary (Henkelman group)",
        "# Download: theory.cm.utexas.edu/bader/",
        "if os.path.exists('AECCAR0') and os.path.exists('AECCAR2'):",
        "    print('Running chgsum.pl AECCAR0 AECCAR2 ...')",
        "    subprocess.run(['chgsum.pl', 'AECCAR0', 'AECCAR2'], check=True)",
        "    print('Running bader CHGCAR -ref CHGCAR_sum ...')",
        "    subprocess.run(['bader', 'CHGCAR', '-ref', 'CHGCAR_sum'], check=True)",
        "    # Parse ACF.dat",
        "    if os.path.exists('ACF.dat'):",
        "        print('\\nBader charges (ACF.dat):')",
        "        print(open('ACF.dat').read()[:2000])",
        "        # Bader charge = Z_ion - q_bader (charge transferred to/from atom)",
        "        import numpy as np",
        "        z_ions = atoms.get_atomic_numbers()",
        "        lines_acf = [l for l in open('ACF.dat') if l.strip() and not l.startswith('-')]",
        "        bader_charges = []",
        "        for line in lines_acf[2:2+len(atoms)]:",  # skip header
        "            cols = line.split()",
        "            if len(cols) >= 5:",
        "                bader_charges.append(float(cols[4]))",
        "        if bader_charges:",
        "            for i, (z, q) in enumerate(zip(z_ions, bader_charges)):",
        "                xfer = z - q",
        "                sym = atoms[i].symbol",
        "                print(f'  Atom {i:3d} ({sym:3s}): Bader charge = {q:.3f} e   charge transfer = {xfer:+.3f} e')",
        "else:",
        "    print('AECCAR files not found — check that LAECHG=True in INCAR.')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 11. Charge density difference (CDD)
# ─────────────────────────────────────────────────────────────────────────────
def script_cdd(
    encut: int = 400,
    kpoints: str = "8 8 1",
    adsorbate: str = "adsorbate",
    surface: str = "surface",
    **_kw,
) -> str:
    """CDD: 3 static calcs (AB, A, B) → ρ_diff = ρ_AB − ρ_A − ρ_B."""
    kpts = [int(x) for x in kpoints.replace("x"," ").split()[:3]] if kpoints else [8,8,1]
    lines = [
        _header(f"Charge density difference: {adsorbate} on {surface}"),
        "import os, shutil",
        "import numpy as np",
        "from ase.io import read",
        "from ase.io.vasp import read_vasp_chgcar, write_vasp",
        "from ase.calculators.vasp import Vasp",
        "",
        "# ── Step 0: Prepare geometries ──────────────────────────────────────────",
        "# Read the RELAXED combined system (AB)",
        "atoms_AB = read('CONTCAR')  # adsorbate + slab, fully relaxed",
        "",
        "# Split: A = slab only (remove adsorbate atoms), B = adsorbate only",
        "# !! Adjust index slices to match your system !!",
        "n_slab = None   # SET THIS: number of slab atoms",
        "if n_slab is None:",
        "    raise ValueError('Set n_slab = number of slab atoms in atoms_AB')",
        "atoms_A = atoms_AB[:n_slab].copy()   # slab only",
        "atoms_B = atoms_AB[n_slab:].copy()   # adsorbate only",
        "# !! Both A and B MUST use the SAME cell as AB !!",
        "atoms_A.set_cell(atoms_AB.get_cell()); atoms_A.pbc = atoms_AB.pbc",
        "atoms_B.set_cell(atoms_AB.get_cell()); atoms_B.pbc = atoms_AB.pbc",
        "",
        "def _make_calc(directory):",
        "    return Vasp(",
        "        istart=0, icharg=2, ibrion=-1, nsw=0,",
        f"        encut={encut}, kpts={kpts},",
        "        xc='PBE', gamma=True,",
        "        ediff=1e-6, ismear=1, sigma=0.2,",
        "        lwave=False, lcharg=True,  # need CHGCAR for each",
        "        ncore=4, directory=directory,",
        "    )",
        "",
        "# ── Step 1: Three static calculations ───────────────────────────────────",
        "for tag, atms in [('AB', atoms_AB), ('A', atoms_A), ('B', atoms_B)]:",
        "    os.makedirs(tag, exist_ok=True)",
        "    write_vasp(f'{tag}/POSCAR', atms)",
        "    print(f'Running static SCF for {tag} ({len(atms)} atoms) ...')",
        "    atms.set_calculator(_make_calc(tag))",
        "    atms.get_potential_energy()",
        "    print(f'{tag} done.  CHGCAR written to {tag}/CHGCAR')",
        "",
        "# ── Step 2: Compute Δρ = ρ_AB − ρ_A − ρ_B ──────────────────────────────",
        "try:",
        "    from ase.io.vasp import read_vasp_chgcar",
        "    chg_AB = read_vasp_chgcar('AB/CHGCAR')",
        "    chg_A  = read_vasp_chgcar('A/CHGCAR')",
        "    chg_B  = read_vasp_chgcar('B/CHGCAR')",
        "    # Arrays are (nx, ny, nz) charge density grids",
        "    delta_rho = chg_AB['total'] - chg_A['total'] - chg_B['total']",
        "    # Save as numpy array",
        "    np.save('delta_rho.npy', delta_rho)",
        "    print(f'CDD saved to delta_rho.npy  shape={delta_rho.shape}')",
        "    print(f'Δρ range: [{delta_rho.min():.4f}, {delta_rho.max():.4f}] e/Å³')",
        "    print('Visualize: copy AB/CHGCAR, replace data with delta_rho, open in VESTA')",
        "    print('Yellow isosurface = charge accumulation; Blue = charge depletion')",
        "except Exception as ex:",
        "    print(f'CDD post-processing warning: {ex}')",
        "    print('Manual: Δρ = CHGCAR_AB − CHGCAR_A − CHGCAR_B  (vaspkit option 31X)')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 12. Work function (LVHAR → LOCPOT)
# ─────────────────────────────────────────────────────────────────────────────
def script_wf(
    encut: int = 400,
    kpoints: str = "8 8 1",
    system_desc: str = "",
    **_kw,
) -> str:
    """Work function via LOCPOT planar average: φ = E_vacuum − E_Fermi."""
    kpts = [int(x) for x in kpoints.replace("x"," ").split()[:3]] if kpoints else [8,8,1]
    lines = [
        _header(f"Work function — LVHAR=True + LOCPOT planar average — {system_desc or 'slab'}"),
        "from ase.io import read",
        "from ase.calculators.vasp import Vasp",
        "import numpy as np",
        "",
        "atoms = read('CONTCAR')",
        "",
        "calc = Vasp(",
        "    istart=0, icharg=2,",
        "    ibrion=-1, nsw=0,",
        f"    encut={encut},",
        f"    kpts={kpts},",
        "    xc='PBE', gamma=True,",
        "    ediff=1e-6,",
        "    ismear=1, sigma=0.2,",
        "    lvhar=True,    # write LOCPOT (total electrostatic potential)",
        "    ldipol=True,   # dipole correction — critical for asymmetric slabs",
        "    idipol=3,      # correct along z-axis (slab normal)",
        "    lwave=False, lcharg=False,",
        "    ncore=4,",
        ")",
        "atoms.set_calculator(calc)",
        "atoms.get_potential_energy()",
        "",
        "# ── Parse LOCPOT: planar average along z ────────────────────────────────",
        "try:",
        "    from ase.io.vasp import read_vasp_out",
        "    from ase.calculators.vasp import VaspChargeDensity",
        "    locpot = VaspChargeDensity('LOCPOT')",
        "    v = locpot.chg[0]          # 3D potential array",
        "    # Planar average: mean over x,y at each z slice",
        "    v_z = v.mean(axis=(0, 1))  # shape: (nz,)",
        "    nz = len(v_z)",
        "    z_coords = np.linspace(0, atoms.get_cell()[2,2], nz, endpoint=False)",
        "    np.savetxt('locpot_avg.dat', np.column_stack([z_coords, v_z]),",
        "               header='z_Angstrom  V_eV')",
        "    # E_vacuum = max of planar-averaged potential in vacuum region",
        "    # E_Fermi from OUTCAR",
        "    ef = calc.get_fermi_level()",
        "    e_vac = v_z.max()",
        "    wf = e_vac - ef",
        "    print(f'E_Fermi   = {ef:.4f} eV')",
        "    print(f'E_vacuum  = {e_vac:.4f} eV')",
        "    print(f'Work function φ = {wf:.4f} eV')",
        "    print('LOCPOT planar average saved to locpot_avg.dat')",
        "except Exception as ex:",
        "    print(f'LOCPOT parse warning: {ex}')",
        "    print('Manual: vaspkit option 426 (work function from LOCPOT)')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 13. COHP / LOBSTER bonding analysis
# ─────────────────────────────────────────────────────────────────────────────
def script_cohp(
    encut: int = 400,
    kpoints: str = "8 8 1",
    system_desc: str = "",
    atom_pairs: str = "",
    **_kw,
) -> str:
    """COHP bonding analysis: VASP SCF with ISYM=-1, then LOBSTER."""
    kpts = [int(x) for x in kpoints.replace("x"," ").split()[:3]] if kpoints else [8,8,1]
    pair_hint = atom_pairs or "e.g. '1 2' for adsorbate-surface bond"
    lines = [
        _header(f"COHP bonding analysis (VASP + LOBSTER) — {system_desc or 'adsorbate-surface'}"),
        "from ase.io import read",
        "from ase.calculators.vasp import Vasp",
        "import os",
        "",
        "atoms = read('CONTCAR')",
        "",
        "# VASP SCF: ISYM=-1 mandatory — LOBSTER needs all k-points explicitly computed",
        "calc = Vasp(",
        "    istart=0, icharg=2,",
        "    ibrion=-1, nsw=0,",
        f"    encut={encut},",
        f"    kpts={kpts},",
        "    xc='PBE', gamma=True,",
        "    ediff=1e-6,",
        "    ismear=1, sigma=0.2,",
        "    isym=-1,       # *** MANDATORY: break symmetry for LOBSTER ***",
        "    lwave=True,    # LOBSTER reads WAVECAR",
        "    lcharg=True,",
        "    lorbit=11,     # DOSCAR + orbital populations for LOBSTER",
        "    ncore=4,",
        ")",
        "atoms.set_calculator(calc)",
        "atoms.get_potential_energy()",
        "print('VASP SCF done — WAVECAR, CHGCAR, DOSCAR written.')",
        "",
        "# ── Generate LOBSTER mainInput ───────────────────────────────────────────",
        "lobster_input = '''",
        "! LOBSTER mainInput — generated by ChatDFT",
        "! Edit atom pairs to match your adsorbate-surface bond",
        "COHPstartEnergy  -20.0",
        "COHPendEnergy     5.0",
        "usebasisSet       pbeVaspFit2015",
        "! Specify atom pairs for COHP analysis:",
        f"! {pair_hint}",
        "! Example: cohpGenerator from 1 to 5 type Fe type C",
        "cohpGenerator from 1 to 5",
        "saveProjectionToFile",
        "'''.strip()",
        "",
        "with open('lobsterin', 'w') as f:",
        "    f.write(lobster_input)",
        "print('lobsterin written.')",
        "print('Run LOBSTER: lobster   (requires lobster binary: schmeling.ac.at/lobster/)')",
        "print('Output: COHPCAR.lobster — plot with lobsterpy or vesta')",
        "print('Bonding: -ICOHP > 0 = bonding interaction; < 0 = antibonding')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 14. Single-point VASP for NNP training
# ─────────────────────────────────────────────────────────────────────────────
def script_singlepoint(
    encut: int = 450,
    kpoints: str = "4 4 1",
    system_desc: str = "",
    **_kw,
) -> str:
    """Single-point VASP for NNP training: tight EDIFF, ISIF=2 for stress tensor."""
    kpts = [int(x) for x in kpoints.replace("x", " ").split()[:3]] if kpoints else [4, 4, 1]
    lines = [
        _header(f"Single-point VASP for NNP training — {system_desc or 'structure'}"),
        "from ase.io import read, write",
        "from ase.calculators.vasp import Vasp",
        "import numpy as np",
        "import os",
        "",
        "# Read structure (POSCAR or any ASE-readable format)",
        "atoms = read('POSCAR')",
        "",
        "calc = Vasp(",
        "    istart=0, icharg=2,",
        "    ibrion=-1, nsw=0,          # static — no relaxation",
        "    isif=2,                     # compute stress tensor",
        f"    encut={encut},              # keep consistent across ALL structures",
        f"    kpts={kpts},",
        "    xc='PBE', gamma=True,",
        "    prec='Accurate',",
        "    ediff=1e-6,                 # tight convergence for NNP labels",
        "    ismear=1, sigma=0.2,",
        "    lwave=False, lcharg=False,  # skip heavy files",
        "    lreal='Auto',",
        "    nelm=200,",
        "    ncore=4, algo='Fast',",
        ")",
        "atoms.set_calculator(calc)",
        "",
        "# Run single-point calculation",
        "energy = atoms.get_potential_energy()",
        "forces = atoms.get_forces()",
        "try:",
        "    stress = atoms.get_stress()   # Voigt notation [xx,yy,zz,yz,xz,xy]",
        "except Exception:",
        "    stress = None",
        "",
        "# Store labels in atoms.info / arrays",
        "atoms.info['energy'] = energy",
        "atoms.arrays['forces'] = forces",
        "if stress is not None:",
        "    atoms.info['stress'] = stress.tolist()",
        "",
        "# Export as extXYZ frame (append mode for batch runs)",
        "write('output.xyz', atoms, format='extxyz', append=True)",
        "",
        "print(f'Energy: {energy:.6f} eV')",
        "print(f'Max force: {np.abs(forces).max():.4f} eV/Å')",
        "if stress is not None:",
        "    print(f'Stress (Voigt): {stress}')",
        "print('Frame appended to output.xyz')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# 15. HTP batch job script
# ─────────────────────────────────────────────────────────────────────────────
def script_htp_batch(
    db_path: str = "htp_dataset.db",
    encut: int = 450,
    kpoints: str = "4 4 1",
    batch_size: int = 50,
    scheduler: str = "sge",
    **_kw,
) -> str:
    """
    Script that reads pending structures from HTP database, runs single-point
    VASP for each, saves results back to db, exports final extXYZ training set.
    """
    kpts = [int(x) for x in kpoints.replace("x", " ").split()[:3]] if kpoints else [4, 4, 1]
    submit_block_sge = (
        "#!/bin/bash\n"
        "#$ -N htp_batch\n"
        "#$ -cwd\n"
        "#$ -l h_rt=48:00:00\n"
        "#$ -pe shared 16\n"
        "#$ -l h_data=4G\n"
        "module load vasp\n"
        "python htp_batch.py\n"
    ) if scheduler == "sge" else (
        "#!/bin/bash\n"
        "#SBATCH -J htp_batch\n"
        "#SBATCH -N 1\n"
        "#SBATCH --ntasks=16\n"
        "#SBATCH -t 48:00:00\n"
        "module load vasp\n"
        "python htp_batch.py\n"
    )
    lines = [
        _header(f"HTP batch job: single-point VASP for NNP training dataset"),
        "# ── Cluster submission script ─────────────────────────────────────────────",
        f"# Scheduler: {scheduler}",
        f"# Submit with: {'qsub' if scheduler == 'sge' else 'sbatch'} htp_submit.sh",
        "",
        "# ── Python batch driver (htp_batch.py) ───────────────────────────────────",
        "import os",
        "import numpy as np",
        "from ase.io import write",
        "from ase.calculators.vasp import Vasp",
        "from server.execution.htp_agent import HTPDataset",
        "",
        f"DB_PATH = '{db_path}'",
        f"BATCH_SIZE = {batch_size}",
        f"ENCUT = {encut}",
        f"KPTS = {kpts}",
        "",
        "dataset = HTPDataset(db_path=DB_PATH)",
        "",
        "# ── Process pending structures in batches ─────────────────────────────────",
        "pending = dataset.get_pending(limit=BATCH_SIZE)",
        "print(f'Processing {len(pending)} pending structures...')",
        "",
        "for row_id, atoms in pending:",
        "    try:",
        "        calc = Vasp(",
        "            istart=0, icharg=2, ibrion=-1, nsw=0, isif=2,",
        "            encut=ENCUT, kpts=KPTS,",
        "            xc='PBE', gamma=True, prec='Accurate',",
        "            ediff=1e-6, ismear=1, sigma=0.2,",
        "            lwave=False, lcharg=False, lreal='Auto',",
        "            nelm=200, ncore=4, algo='Fast',",
        f"           directory=f'vasp_runs/{{row_id}}',",
        "        )",
        "        atoms.set_calculator(calc)",
        "        energy = atoms.get_potential_energy()",
        "        forces = atoms.get_forces()",
        "        try:",
        "            stress = atoms.get_stress()",
        "        except Exception:",
        "            stress = None",
        "        dataset.mark_done(row_id, energy, forces, stress)",
        "        print(f'  Row {row_id}: E={energy:.4f} eV, done.')",
        "    except Exception as e:",
        "        dataset.mark_failed(row_id, str(e))",
        "        print(f'  Row {row_id}: FAILED — {e}')",
        "",
        "# ── Export final training set ─────────────────────────────────────────────",
        "n_exported = dataset.export_extxyz('training.xyz', only_done=True)",
        "print(f'Exported {n_exported} structures to training.xyz')",
        "print(f'Dataset stats: {dataset.stats()}')",
        "",
        "# ── Cluster submission script ─────────────────────────────────────────────",
        f"SUBMIT_SCRIPT = '''{submit_block_sge}'''",
        "with open('htp_submit.sh', 'w') as f:",
        "    f.write(SUBMIT_SCRIPT)",
        "print('Cluster submission script written to htp_submit.sh')",
    ]
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Dispatch
# ─────────────────────────────────────────────────────────────────────────────
_GENERATORS = {
    "surface":        script_surface,
    "molecule":       script_molecule,
    "geo":            script_geo,
    "relax":          script_geo,
    "freq":           script_freq,
    "frequency":      script_freq,
    "zpe":            script_freq,
    "neb":            script_neb,
    "cineb":          script_neb,
    "ts":             script_neb,
    "gcdft":          script_gcdft,
    "gc_dft":         script_gcdft,
    # Electronic structure — two-step workflow
    "static":         script_static,
    "static_scf":     script_static,
    "scf":            script_static,
    "dos":            script_dos,
    "pdos":           script_dos,
    "band":           script_band,
    "bands":          script_band,
    "elf":            script_elf,
    # New electronic types
    "bader":          script_bader,
    "cdd":            script_cdd,
    "charge_density_difference": script_cdd,
    "work_function":  script_wf,
    "wf":             script_wf,
    "cohp":           script_cohp,
    "coop":           script_cohp,
    "lobster":        script_cohp,
    # NNP training
    "singlepoint":    script_singlepoint,
    "singlepoint_nnp": script_singlepoint,
    "nnp":            script_singlepoint,
    "nnp_sp":         script_singlepoint,
    "htp_batch":      script_htp_batch,
}

_FILENAMES = {
    "surface":        "ase-surface.py",
    "molecule":       "ase-molecule.py",
    "geo":            "ase-geo.py",
    "relax":          "ase-geo.py",
    "freq":           "ase-freq.py",
    "frequency":      "ase-freq.py",
    "zpe":            "ase-freq.py",
    "neb":            "ase-neb.py",
    "cineb":          "ase-neb.py",
    "ts":             "ase-neb.py",
    "gcdft":          "ase-gcdft.py",
    "gc_dft":         "ase-gcdft.py",
    "static":         "ase-static.py",
    "static_scf":     "ase-static.py",
    "scf":            "ase-static.py",
    "dos":            "ase-dos.py",
    "pdos":           "ase-dos.py",
    "band":           "ase-band.py",
    "bands":          "ase-band.py",
    "elf":            "ase-elf.py",
    "bader":          "ase-bader.py",
    "cdd":            "ase-cdd.py",
    "charge_density_difference": "ase-cdd.py",
    "work_function":  "ase-wf.py",
    "wf":             "ase-wf.py",
    "cohp":           "ase-cohp.py",
    "coop":           "ase-cohp.py",
    "lobster":        "ase-cohp.py",
    "singlepoint":    "ase-singlepoint.py",
    "singlepoint_nnp": "ase-singlepoint.py",
    "nnp":            "ase-singlepoint.py",
    "nnp_sp":         "ase-singlepoint.py",
    "htp_batch":      "htp_batch.py",
}


def generate_script(calc_type: str, system: Dict[str, Any] = None, params: Dict[str, Any] = None) -> str:
    """
    Generate an ASE calculation script.
    calc_type: one of 'surface','molecule','geo','freq','neb','gcdft',
               'static','dos','pdos','band','elf','bader','cdd','work_function','cohp'
    system: dict with element, facet, surface_type, etc.
    params: dict with calculation-specific parameters
    """
    key = (calc_type or "geo").lower().strip()
    fn = _GENERATORS.get(key, script_geo)
    merged = {}
    if system: merged.update(system)
    if params: merged.update(params)
    return fn(**merged)


def script_filename(calc_type: str) -> str:
    return _FILENAMES.get((calc_type or "geo").lower(), f"ase-{calc_type}.py")
